# Generated by Django 4.0.3 on 2022-03-11 06:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_talk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='talk',
            name='dt',
        ),
        migrations.AddField(
            model_name='talk',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
